version: "3.9"

services:
  coworking-app:
    build: .
    container_name: coworking-app
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.railway.internal:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ""
